# Generated by Django 6.0.4 on 2026-09-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0008_remove_report_data_remove_reportsubmission_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistlog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='checklistlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='control_dashboard.branch'),
        ),
        migrations.AddField(
            model_name='checklistlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='control_dashboard.department'),
        ),
        migrations.AddConstraint(
            model_name='checklistlog',
            constraint=models.UniqueConstraint(fields=('checklist', 'user', 'branch', 'department', 'log_date'), name='unique_checklist_log_per_unit_per_day'),
        ),
        migrations.AlterModelTable(
            name='checklistlog',
            table=None,
        ),
        migrations.RemoveField(
            model_name='checklistlog',
            name='updated_at',
        ),
    ]
