# Generated by Django 6.0.4 on 2026-09-19 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0009_alter_checklistlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('branch_code', models.CharField(blank=True, default='', max_length=50)),
                ('today', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('parent_gl', models.CharField(blank=True, default='', max_length=50)),
                ('gl_code', models.CharField(blank=True, default='', max_length=50)),
                ('descr', models.CharField(blank=True, default='', max_length=500)),
                ('ccy', models.CharField(blank=True, default='', max_length=10)),
                ('open_bal_lcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dr_bal_lcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cr_bal_lcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('close_bal_lcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('open_bal_fcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dr_bal_fcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cr_bal_fcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('close_bal_fcy', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gl_status', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row_index', models.IntegerField(default=0)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_entries', to='control_dashboard.report')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_entries', to='control_dashboard.userprofile')),
            ],
            options={
                'ordering': ['report_date', 'row_index'],
                'indexes': [models.Index(fields=['report_date', 'uploaded_by'], name='control_das_report__fd2c9f_idx')],
            },
        ),
    ]
