# Generated by Django 6.0.4 on 2026-09-19 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0010_trialbalanceentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhocdeduction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ad-Hoc Score Entry', 'verbose_name_plural': 'Ad-Hoc Score Entries'},
        ),
        migrations.AddField(
            model_name='adhocdeduction',
            name='points_added',
            field=models.IntegerField(default=0, help_text='Number of points ADDED/AWARDED (0-100)'),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='created_by',
            field=models.ForeignKey(help_text='Supervisor who created the entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deductions', to='control_dashboard.userprofile'),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='points',
            field=models.IntegerField(default=0, help_text='Number of points DEDUCTED (0-100)'),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the score change', null=True),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='user',
            field=models.ForeignKey(help_text='The team member this score entry applies to', on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_deductions', to='control_dashboard.userprofile'),
        ),
        migrations.AddIndex(
            model_name='adhocdeduction',
            index=models.Index(fields=['points_added'], name='control_das_points__9a12e5_idx'),
        ),
    ]
