# Generated by Django 6.0.4 on 2026-09-20 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0011_alter_adhocdeduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('uploaded', 'Uploaded (Exception Data)')], default='assigned', max_length=50),
        ),
        migrations.CreateModel(
            name='SubmittedReportScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('had_attachment', models.BooleanField(default=False)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('auto_score', models.IntegerField(default=0)),
                ('minutes_late', models.IntegerField(default=0)),
                ('manual_score', models.IntegerField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_score', to='control_dashboard.report')),
            ],
            options={
                'db_table': 'submitted_report_scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
