# Generated by Django 6.0.4 on 2026-09-20 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0012_alter_report_status_submittedreportscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedreportscore',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The member who actually sent the submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_report_scores', to='control_dashboard.userprofile'),
        ),
    ]
