# Generated by Django 6.0.4 on 2026-09-20 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0013_submittedreportscore_submitted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submittedreportscore',
            options={'ordering': ['-sent_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='submittedreportscore',
            name='period_deadline_at',
            field=models.DateTimeField(blank=True, help_text='Deadline of the recurrence period this submission belongs to.', null=True),
        ),
        migrations.AddField(
            model_name='submittedreportscore',
            name='snapshot_final_score',
            field=models.IntegerField(blank=True, help_text='Final score as computed at submission time. Used for team performance.', null=True),
        ),
        migrations.AlterField(
            model_name='submittedreportscore',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_scores', to='control_dashboard.report'),
        ),
        migrations.AddIndex(
            model_name='submittedreportscore',
            index=models.Index(fields=['submitted_by', 'sent_at'], name='submitted_r_submitt_9a56a3_idx'),
        ),
        migrations.AddIndex(
            model_name='submittedreportscore',
            index=models.Index(fields=['report', 'period_deadline_at'], name='submitted_r_report__b7c386_idx'),
        ),
    ]
