# Generated by Django 6.0.4 on 2026-09-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0014_alter_submittedreportscore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, help_text='Denormalized from Report.report_type for faster filtering', max_length=200)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('excel_import', models.ForeignKey(blank=True, help_text='The raw Excel import this batch was parsed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_batches', to='control_dashboard.reportexcelimport')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_batches', to='control_dashboard.userprofile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_batches', to='control_dashboard.report')),
            ],
            options={
                'db_table': 'exception_batches',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0, help_text='S/N from the original report')),
                ('branch_unit', models.CharField(blank=True, db_index=True, default='', help_text='Branch or unit the exception belongs to', max_length=200)),
                ('exception', models.TextField(blank=True, default='', help_text='Description of the exception / finding')),
                ('date_noted', models.DateField(blank=True, db_index=True, help_text='Date the exception was first observed', null=True)),
                ('date_noted_raw', models.CharField(blank=True, default='', help_text='Original string, in case parsing failed', max_length=50)),
                ('target_closure_date', models.DateField(blank=True, db_index=True, help_text='Date by which the exception should be closed', null=True)),
                ('target_closure_date_raw', models.CharField(blank=True, default='', help_text='Original string, in case parsing failed', max_length=50)),
                ('category', models.CharField(blank=True, db_index=True, default='', help_text='Category / classification of the exception', max_length=200)),
                ('responsible_officer', models.CharField(blank=True, db_index=True, default='', help_text='Officer responsible for resolving the exception', max_length=200)),
                ('supervisor', models.CharField(blank=True, default='', help_text='Supervisor overseeing the exception', max_length=200)),
                ('auditee_response', models.TextField(blank=True, default='', help_text='Response from the auditee / responsible party')),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], db_index=True, default='open', help_text='Current status of the exception', max_length=50)),
                ('status_raw', models.CharField(blank=True, default='', help_text='Original status string as it appeared in the file', max_length=100)),
                ('income_cost_saved', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Monetary value of income recovered or cost saved', max_digits=18)),
                ('income_cost_saved_raw', models.CharField(blank=True, default='', help_text='Original string, in case parsing failed', max_length=50)),
                ('source_row_index', models.IntegerField(default=0, help_text='Row index in the original Excel file (for traceability)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='control_dashboard.exceptionbatch')),
            ],
            options={
                'db_table': 'exception_records',
                'ordering': ['batch', 'serial_number', 'source_row_index'],
            },
        ),
        migrations.AddIndex(
            model_name='exceptionbatch',
            index=models.Index(fields=['report_type', 'imported_at'], name='exception_b_report__e88645_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['batch', 'status'], name='exception_r_batch_i_ec3cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['branch_unit', 'status'], name='exception_r_branch__b0f257_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['responsible_officer'], name='exception_r_respons_700671_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['target_closure_date'], name='exception_r_target__5d8e34_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['category'], name='exception_r_categor_f0f027_idx'),
        ),
    ]
