# Generated by Django 6.0.4 on 2026-09-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0015_exceptionbatch_exceptionrecord_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exceptionbatch',
            name='exception_b_report__e88645_idx',
        ),
        migrations.AlterModelOptions(
            name='exceptionrecord',
            options={'ordering': ['report', 'serial_number', 'source_row_index']},
        ),
        migrations.RemoveIndex(
            model_name='exceptionrecord',
            name='exception_r_batch_i_ec3cd1_idx',
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='excel_import',
            field=models.ForeignKey(blank=True, help_text='The raw Excel import this record was parsed from (for traceability)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_records', to='control_dashboard.reportexcelimport'),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='report',
            field=models.ForeignKey(help_text='The Report (Excel data container) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_records', to='control_dashboard.report'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['report', 'status'], name='exception_r_report__396b39_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['excel_import', 'status'], name='exception_r_excel_i_6409d0_idx'),
        ),
        migrations.RemoveField(
            model_name='exceptionrecord',
            name='batch',
        ),
        migrations.DeleteModel(
            name='ExceptionBatch',
        ),
    ]
