# Generated by Django 6.0.4 on 2026-09-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0016_remove_exceptionbatch_exception_b_report__e88645_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportexcelcell',
            name='row',
        ),
        migrations.RemoveField(
            model_name='reportexcelimport',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportexcelrow',
            name='import_record',
        ),
        migrations.RemoveIndex(
            model_name='exceptionrecord',
            name='exception_r_excel_i_6409d0_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='excel_headers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='report',
            field=models.ForeignKey(blank=True, help_text='The Report (Excel data container) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_records', to='control_dashboard.report'),
        ),
        migrations.DeleteModel(
            name='ReportExcelCell',
        ),
        migrations.DeleteModel(
            name='ReportExcelRow',
        ),
        migrations.RemoveField(
            model_name='exceptionrecord',
            name='excel_import',
        ),
        migrations.DeleteModel(
            name='ReportExcelImport',
        ),
    ]
