# Generated by Django 6.0.4 on 2026-09-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0017_remove_reportexcelcell_row_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submittedreportscore',
            name='submitted_r_submitt_9a56a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='submittedreportscore',
            name='submitted_r_report__b7c386_idx',
        ),
        migrations.DeleteModel(
            name='SubmittedReportScore',
        ),
    ]
