# Generated by Django 5.2.17 on 2026-09-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0018_remove_submittedreportscore_submitted_r_submitt_9a56a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Admin-uploaded profile picture (optional).', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deductions', to='control_dashboard.userprofile'),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='points_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='task_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhocdeduction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_deductions', to='control_dashboard.userprofile'),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='auditee_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='branch_unit',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='date_noted',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='date_noted_raw',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='exception',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='income_cost_saved',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='income_cost_saved_raw',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_records', to='control_dashboard.report'),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='responsible_officer',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='source_row_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], db_index=True, default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='status_raw',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='target_closure_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='target_closure_date_raw',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
