# Generated by Django 5.2.17 on 2026-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0019_userprofile_avatar_alter_activitylog_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text="Only used when assignment_scope='specific'.", related_name='scoped_branches', to='control_dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='branch',
            name='assignment_scope',
            field=models.CharField(choices=[('cc', 'Cluster Control'), ('hc', 'Head Office Control'), ('specific', 'Specific Users')], default='cc', help_text='Who can see this branch in their dashboard.', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='department',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text="Only used when assignment_scope='specific'.", related_name='scoped_departments', to='control_dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='department',
            name='assignment_scope',
            field=models.CharField(choices=[('cc', 'Cluster Control'), ('hc', 'Head Office Control'), ('specific', 'Specific Users')], default='cc', help_text='Who can see this department in their dashboard.', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
