# Generated by Django 5.2.17 on 2026-10-01 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0020_branch_assigned_users_branch_assignment_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_addresses', models.TextField(help_text='Comma-separated list of To: addresses at send time.')),
                ('cc_addresses', models.TextField(blank=True, default='', help_text='Comma-separated list of CC: addresses at send time.')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'sent_emails',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sender', 'sent_at'], name='sent_emails_sender__ec125c_idx'), models.Index(fields=['report_type', 'sent_at'], name='sent_emails_report__c43d81_idx'), models.Index(fields=['status', 'sent_at'], name='sent_emails_status_7879c3_idx')],
            },
        ),
    ]
