# Generated by Django 5.2.17 on 2026-10-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0021_sentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, help_text="User-chosen report type (e.g. 'Weekly Exceptions Report').", max_length=200)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('excel_headers', models.TextField(blank=True, default='', help_text='Comma-separated original Excel headers, preserved for rendering.')),
                ('row_count', models.IntegerField(default=0, help_text='Number of exception rows stored for this upload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exception_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, help_text='The trading day this trial balance applies to.')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.IntegerField(default=0, help_text='Number of data rows stored for this upload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trial_balance_uploads',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='exceptionrecord',
            options={'ordering': ['upload', 'serial_number', 'source_row_index']},
        ),
        migrations.RemoveIndex(
            model_name='exceptionrecord',
            name='exception_r_report__396b39_idx',
        ),
        migrations.RenameIndex(
            model_name='trialbalanceentry',
            new_name='trial_balan_report__d31081_idx',
            old_name='control_das_report__fd2c9f_idx',
        ),
        migrations.RemoveField(
            model_name='exceptionrecord',
            name='report',
        ),
        migrations.RemoveField(
            model_name='trialbalanceentry',
            name='report',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('uploaded', 'Uploaded (Legacy — do not use)')], default='assigned', max_length=50),
        ),
        migrations.AlterModelTable(
            name='trialbalanceentry',
            table='trial_balance_entries',
        ),
        migrations.AddField(
            model_name='exceptionupload',
            name='uploaded_by',
            field=models.ForeignKey(help_text='The user who uploaded this file.', on_delete=django.db.models.deletion.CASCADE, related_name='exception_uploads', to='control_dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='The upload this row belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_records', to='control_dashboard.exceptionupload'),
        ),
        migrations.AddIndex(
            model_name='exceptionrecord',
            index=models.Index(fields=['upload', 'status'], name='exception_r_upload__8b0d71_idx'),
        ),
        migrations.AddField(
            model_name='trialbalanceupload',
            name='uploaded_by',
            field=models.ForeignKey(help_text='The user who uploaded this file.', on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_uploads', to='control_dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='trialbalanceentry',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='The upload this row belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='control_dashboard.trialbalanceupload'),
        ),
        migrations.AddIndex(
            model_name='trialbalanceentry',
            index=models.Index(fields=['upload', 'row_index'], name='trial_balan_upload__a5b1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionupload',
            index=models.Index(fields=['report_type'], name='exception_u_report__ec308c_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionupload',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='exception_u_uploade_8c5a01_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbalanceupload',
            index=models.Index(fields=['report_date'], name='trial_balan_report__f1b698_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbalanceupload',
            index=models.Index(fields=['uploaded_by', 'report_date'], name='trial_balan_uploade_a16cdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='trialbalanceupload',
            constraint=models.UniqueConstraint(fields=('report_date',), name='unique_trial_balance_per_day'),
        ),
    ]
