# Generated by Django 5.2.17 on 2026-10-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0022_add_upload_fks_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='manual_deduction',
            field=models.IntegerField(default=0, help_text='Points deducted by a supervisor (0–100).'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='override_reason',
            field=models.TextField(blank=True, default='', help_text='Optional note explaining the deduction.'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='scored_at',
            field=models.DateTimeField(blank=True, help_text='When the deduction was last edited.', null=True),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='scored_by',
            field=models.ForeignKey(blank=True, help_text='Supervisor who last edited the deduction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_emails', to='control_dashboard.userprofile'),
        ),
    ]
