# Generated by Django 5.2.17 on 2026-10-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0023_sentemail_manual_deduction_sentemail_override_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('create', 'Create new checklist'), ('modify', 'Modify existing checklist'), ('delete', 'Delete checklist'), ('add_task', 'Add task to checklist')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by requester')], db_index=True, default='pending', max_length=12)),
                ('current_snapshot', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('justification', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_request', to='control_dashboard.checklist')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_requests', to='control_dashboard.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checklist_requests', to='control_dashboard.userprofile')),
                ('target_checklist', models.ForeignKey(blank=True, help_text='Null for CREATE requests.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='control_dashboard.checklist')),
            ],
            options={
                'db_table': 'checklist_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='checklist_c_status_5db0af_idx'), models.Index(fields=['requester', '-created_at'], name='checklist_c_request_c0b041_idx'), models.Index(fields=['target_checklist', 'status'], name='checklist_c_target__563c93_idx')],
            },
        ),
    ]
